algoritmo "EstruturaRepetição_02"
// Função : Trabalhando com estrutura de repetição
// Autor : Paulo H Melo
// Data : 30/04/2021
// Seção de Declarações 
var
   contador: inteiro
inicio
// Seção de Comandos
      contador <- 10
      Enquanto (contador >= 0) faca
               Escreval(contador)
               contador <- contador - 2
      FimEnquanto
      Escreval("Terminei de contar")
fimalgoritmo
