algoritmo "EstruturaRepetição_01"
// Função : Trabalhando com estrutura de repetição
// Autor : Paulo H Melo
// Data : 30/04/2021
// Seção de Declarações 
var
   contador: inteiro
inicio
// Seção de Comandos
      contador <- 0
      Enquanto (contador <= 100) faca
               Escreval(contador)
               contador <- contador + 10
      FimEnquanto
      Escreval("Terminei de contar")
fimalgoritmo
